map_update_interval: 2.0
maxRange: 5.5
maxUrange: 5.0
minimumScore: 50
linearUpdate: 0.1
angularUpdate: 0.1
temporalUpdate: 0.5
delta: 0.05
lskip: 10
particles: 120
sigma: 0.05
kernelSize: 1
lstep: 0.1
astep: 0.1
iterations: 5
lsigma: 0.075
ogain: 3.0
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
resampleThreshold: 0.5
xmin: -20.0
ymin: -20.0
xmax: 20.0
ymax: 20.0
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
